### ISSUE TITLE
useLiveQuery() error in production build with latest Nextjs version

### ISSUE THREAD

**Issue by Mrbzs** [sanity-io/preview-kit#430]
Error appears in production build using `useLiveQuery()` in latest version of Nextjs (13.4.12) when content in Sanity is changed and live preview doesn't work. Here's the error from the browser console:

```
Uncaught TypeError: this.model.objectGetKeys is not a function
    at t.inputKey (516.226b7de8a30a8ce7.js:1:1891)
    at t.processPushField (516.226b7de8a30a8ce7.js:1:3454)
    at t.processPushFieldBlank (516.226b7de8a30a8ce7.js:1:3894)
    at t.process (516.226b7de8a30a8ce7.js:1:1666)
    at o (516.226b7de8a30a8ce7.js:1:5499)
    at tj (516.226b7de8a30a8ce7.js:1:45928)
    at x (516.226b7de8a30a8ce7.js:1:51834)
    at next (516.226b7de8a30a8ce7.js:1:51555)
    at q.<anonymous> (516.226b7de8a30a8ce7.js:1:50932)
    at O.dispatchEvent (266.5088434fc39e1b1c.js:5:7132)
```

## Expected Behavior
There shouldn't be errors and live preview should work when content is updated in Sanity.

## Current Behavior
Content doesn't update and an error is thrown in browser console.

## Steps to Reproduce
I have created a simple [GitHub repo](https://github.com/Mrbzs/preview-kit-next) to demonstrate the issue.

1. Clone the repo
2. Copy environment variables from `env.local.example` to `env.local`. Needs a simple Sanity project with a `user` schema that has a `name` field
3. Run the production build. Repo's `README.md` has commands if needed
4. Update a user document in Sanity and the error appears in browser console

## Other Information
- It works in development server but not in production build
- It works with slightly older versions of Nextjs. One version that I have tried is 13.4.7 and it worked in this version

**Comment by stipsan** [comment]
Hi, thanks for your detailed reproduction instructions, they've been instrumental in fixing this. Using [v2.4.7](https://github.com/sanity-io/preview-kit/releases/tag/v2.4.7) I'm no longer able to reproduce the bug, can you verify it on your end? ☺️

**Comment by Mrbzs** [comment]
Hi @stipsan, thanks a lot. It's working from my end as well! 

Out of curiousity, would you mind telling me what was the issue and how did you fix it?

**Comment by stipsan** [comment]
Sure, the core issue were that a new version of the minifier in Next.js removed some code in the [package used to patch the documents cache with updates as they come in](https://github.com/sanity-io/mendoza-js). This package haven't been changed in 3 years, so while it was written in ES6 it was still shipping ES5. 
By refactoring it to use our modern build tooling that outputs ES6 and ESM the Next.js minifier correctly identified unused and used code 🙌
