### ISSUE TITLE
Request: option to pass groq-store config

### ISSUE THREAD

**Issue by danieljb** [sanity-io/preview-kit#63]
Hi. I am currently exploring Sanity + Remix and recently tried out `preview-kit`. Getting live previews working is super easy, so thanks a lot for creating it. There’s however one thing that I struggle to get to work: **highlighting documents that contain unpublished changes**.

For that to happen I’d use GROQ to query for the `_id` of a document being prefixed with `drafts.`. With `preview-kit` initializing the `groq-store` with `overlayDrafts: true` this is not possible.

I’d propose to enable either one of the following options: 
1. pass [`groq-store` config options](https://github.com/sanity-io/groq-store/#usage) to [`preview-kit`’s `definePreview`](https://github.com/sanity-io/preview-kit#usage)
2. allow passing a custom [`importGroqStore` function](https://github.com/sanity-io/preview-kit/blob/main/src/definePreview.ts#L41)

A current alternative right now would be a custom implementation of `definePreview` or using the “private” `_definePreview` function for initialization – but this kind of defeats the purpose of using `preview-kit`.

**Comment by stipsan** [comment]
Hey, we recommend using the `_definePreview` function for now as mentioned:
```tsx
import {
  _definePreview,
  _checkAuth,
  _lazyEventSourcePolyfill,
  _lazyGroqStore,
  _preloadQuery,
  PreviewConfig,
  UsePreview,
} from '@sanity/preview-kit'
import { suspend } from 'suspend-react'
import type { Config, GroqStore } from '@sanity/groq-store'

export const definePreview = (config: PreviewConfig): UsePreview =>
  _definePreview({
    ...config,
    importEventSourcePolyfill: () =>
      suspend(
        () => _lazyEventSourcePolyfill(),
        ['@sanity/preview-kit', 'event-source-polyfill']
      ),
    importGroqStore: () =>
      suspend(async () => {
        const createGroqStore = await _lazyGroqStore()
        return (config: Config): GroqStore =>
          createGroqStore({ ...config, overlayDrafts: false })
      }, ['@sanity/preview-kit', '@sanity/groq-store']),
    preload: (store, query, params) =>
      suspend(
        () => _preloadQuery(store, query, params),
        [
          '@sanity/preview-kit',
          'preload',
          query,
          JSON.stringify(params ?? null),
        ]
      ),
    checkAuth: (projectId, token) =>
      suspend(
        () => _checkAuth(projectId, token),
        ['@sanity/preview-kit', 'checkAuth', projectId, token]
      ),
  })
```
We're exporting `_definePreview` to give an escape hatch for cases like yours. If we didn't want people to use it we would simply not export it. Underscored exports don't follow semver though and could be breaking in any release.

I agree with your "this kind of defeats the purpose of using preview-kit" comment on doing so much work and implement a `_definePreview` wrapper just to be able to query if documents have unpublished changes or not. I think a better fix would be for `groq-store` and `overlayDrafts: true` to preserve the `drafts.` prefix on its ID. That is a better match, conceptually, to what the Studio is doing internally and how it works if you're writing studio plugins 🤔 

I'll leave this issue open and up to date with what we decide to do in `groq-store` :)

**Comment by danieljb** [comment]
Hi stipsan, thanks for the fast reply and the example code. Sounds good, I’ll use `_definePreview` for now and keep an eye on the issues here and in `groq-store`.

Keeping the `drafts.` prefix would be great. At least that’s what I expected and it took me a while to figure out what was going on under the hood.

**Comment by danieljb** [comment]
Quick update: this actually works nicely. Obviously had to update the GROQ query to intentionally fetch draft documents.

Also had to copy over the [`_preloadQuery` function](https://github.com/sanity-io/preview-kit/blob/main/src/definePreview.ts#L244-L247) as it is not currently exported from `preview-kit`.
